spring.datasource.url: jdbc:mysql://localhost/chat_db
  ?autoReconnect=true&
  useUnicode=true&
  createDatabaseIfNotExist=true&
  characterEncoding=utf-8
spring.datasource.username: worker
spring.datasource.password: Qwe1231_
spring.jpa.hibernate.ddl-auto: update
